export const FETCH_ALL_ARTICLE_REQUEST = 'FETCH_ALL_ARTICLE_REQUEST';
export const FETCH_ALL_ARTICLE_SUCCESS = 'FETCH_ALL_ARTICLE_SUCCESS';
export const FETCH_ALL_ARTICLE_ERROR = 'FETCH_ALL_ARTICLE_ERROR';
